#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.

if [ -e "school" ]; then
    echo "school file exists"

    if [ ! -s "school" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
