#!/usr/bin/env bash
# Iterate 10 times using a while loop but 9th itiration
i=0
while [ $i -lt 10 ]
do
    if [ $i -lt 9 ];then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
