#!/usr/bin/env bash
# Iterate 10 times using a while loop but 4,8th itiration
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 4 ];then
		echo "bad luck"
	elif [   $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
