#!/usr/bin/env bash
# Iterate 10 times using a while loop but 4,9,17th itiration
i=1
while [ $i -le 20 ]
do
    case $i in
		4)
		echo "4"
		echo "bad luck from China"
		;;
		9)
		echo "9"
		echo "bad luck from Japan"
		;;
		17)
		echo "17"
		echo "bad luck from Italy"
		;;
	*)
		echo "$i"
		exit
	esac
	i=$((i+1))
done
