#!/usr/bin/env bash
# Iterate 10 times using a while loop but 4,9,17th itiration
i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ];then
		echo "4"
		echo "bad luck from China"
	elif [   $i -eq 9 ]; then
		echo "9"
		echo "bad luck from Japan"
	elif [   $i -eq 17 ];then
		echo "17"
		echo "bad luck from Italy"
	else
	echo "$i"
	fi
	i=$((i+1))
done
